// Parametric Helical Spiral Marble Run (Single Helix)
// Generated by generate_spiral_marble_run.py

// Parameters
marble_od = 16.0;  // marble diameter
wire_od = 2.1;  // wire diameter
track_sep = 10.0;  // clear space between rails (not used in single helix)
outer_radius = 70; // 150.0;  // starting radius
inner_radius = 1.0;  // ending radius (center)
vertical_sep = -2.1;  // vertical distance per revolution (+ = center higher, - = center lower)
segments_per_revolution = 120;  // resolution

// Calculated values
radial_step = track_sep + wire_od;  // radial distance decrease per revolution
num_revolutions = (outer_radius - inner_radius) / radial_step;  // automatically calculate revolutions to reach inner_radius
total_segments = num_revolutions * segments_per_revolution;
total_vertical = vertical_sep * num_revolutions;
marble_offset = track_sep / 2 + wire_od / 2;  // distance from wire center to marble center

// Calculate total wire length
function calc_wire_length() =
    let(
        lengths = [
            for (i = [0 : total_segments - 1])
                let(
                    t = i / total_segments,
                    angle = t * num_revolutions * 360,
                    revolutions_completed = t * num_revolutions,
                    radius = outer_radius - revolutions_completed * radial_step,
                    z = t * total_vertical,
                    x = radius * cos(angle),
                    y = radius * sin(angle),

                    t_next = (i + 1) / total_segments,
                    angle_next = t_next * num_revolutions * 360,
                    revolutions_completed_next = t_next * num_revolutions,
                    radius_next = outer_radius - revolutions_completed_next * radial_step,
                    z_next = t_next * total_vertical,
                    x_next = radius_next * cos(angle_next),
                    y_next = radius_next * sin(angle_next),

                    dx = x_next - x,
                    dy = y_next - y,
                    dz = z_next - z,
                    segment_length = sqrt(dx*dx + dy*dy + dz*dz)
                )
                segment_length
        ]
    )
    sum(lengths);

function sum(v, i=0, acc=0) = i >= len(v) ? acc : sum(v, i+1, acc + v[i]);

wire_length = calc_wire_length();

echo(str("Number of revolutions: ", num_revolutions));
echo(str("Total wire length: ", wire_length, " mm"));

// Single helix spiral module
module spiral_track() {
    for (i = [0 : total_segments - 1]) {
        t = i / total_segments;  // parameter from 0 to 1
        angle = t * num_revolutions * 360;  // angle in degrees
        revolutions_completed = t * num_revolutions;
        radius = outer_radius - revolutions_completed * radial_step;  // decrease by (track_sep + wire_od) per revolution
        z = t * total_vertical;  // vertical position

        // Calculate position
        x = radius * cos(angle);
        y = radius * sin(angle);

        // Draw wire segments
        if (i < total_segments - 1) {
            // Calculate next segment position
            t_next = (i + 1) / total_segments;
            angle_next = t_next * num_revolutions * 360;
            revolutions_completed_next = t_next * num_revolutions;
            radius_next = outer_radius - revolutions_completed_next * radial_step;
            z_next = t_next * total_vertical;
            x_next = radius_next * cos(angle_next);
            y_next = radius_next * sin(angle_next);

            // Single wire segment
            hull() {
                translate([x, y, z])
                    sphere(d=wire_od, $fn=8);
                translate([x_next, y_next, z_next])
                    sphere(d=wire_od, $fn=8);
            }
        }
    }
}

// Function to calculate marble position along spiral at time t (0 to 1)
// The marble alternates which side of the wire it's on each revolution
function marble_position(t) =
    let(
        angle = t * num_revolutions * 360,
        revolutions_completed = t * num_revolutions,
        radius = outer_radius - revolutions_completed * radial_step - radial_step/2 - 1.5,
        z = t * total_vertical + marble_od/3,

        // Calculate which side of the wire the marble is on
        // Alternates each revolution: even revolutions on one side, odd on the other
        revolution_number = floor(revolutions_completed),
        side = (revolution_number % 2 == 0) ? 1 : -1,

        // Offset the marble perpendicular to the spiral direction
        // We need to find the perpendicular direction (inward/outward)
        angle_rad = angle * PI / 180,
        x_wire = radius * cos(angle),
        y_wire = radius * sin(angle),

        // Perpendicular vector (tangent rotated 90 degrees)
        // For a spiral, we approximate locally as circular
        perp_x = -sin(angle_rad),
        perp_y = cos(angle_rad),

        // Position marble offset from wire
        x = x_wire + side * perp_x * marble_offset,
        y = y_wire + side * perp_y * marble_offset
    )
    [x, y, z];

// Animated marble
color("red")
    translate(marble_position($t))
        sphere(d=marble_od);

// Render the spiral track
spiral_track();
